openapi: 3.1.0
info:
  version: 0.1.0
  title: g
paths:
  /accounts/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountId:
                    type: integer
                required:
                  - name
        400:
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
  /accounts/{id}/balance:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: integer
        404:
          description: Not Found
  /accounts/{id}/mint:
    post:
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
              required:
                - amount
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: integer
                required:
                  - name
        400:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: integer
                required:
                  - name
        404:
          description: Not Found
