openapi: 3.1.0
info:
  version: 0.1.0
  title: g
paths:
  /accounts/{id}/balance:
    get:
      parameters:
        - $ref: '#/components/parameters/AccountId'
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: integer
        404: {}
  /accounts/{id}/transactions:
    get:
      parameters:
        - $ref: '#/components/parameters/AccountId'
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: integer
        404: {}
  /accounts/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountId:
                    type: integer
                required:
                  - name
        400:
          content:
            text/plain:
              schema:
                type: string
  /accounts/{id}/mint:
    post:
      parameters:
        - $ref: '#/components/parameters/AccountId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
              required:
                - amount
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: integer
        400:
          content:
            text/plain:
              schema:
                type: string
        404: {}
  /accounts/{id}/spend:
    post:
      parameters:
        - $ref: '#/components/parameters/AccountId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
              required:
                - amount
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: integer
        400:
          content:
            text/plain:
              schema:
                type: string
        404: {}
  /accounts/{id}/transfer:
    post:
      parameters:
        - $ref: '#/components/parameters/AccountId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                to:
                  type: integer
              required:
                - amount
                - to
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: integer
        400:
          content:
            text/plain:
              schema:
                type: string
        404: {}
components:
  parameters:
    AccountId:
      in: path
      name: id
      schema:
        type: integer
      required: true
